In [1]:
import pandas as pd
from lifelines import CoxPHFitter

In [2]:
cox_data = pd.DataFrame({
    "age": [63, 55, 71, 49, 66, 58, 74, 52],
    "hpv_positive": [1, 0, 1, 1, 0, 1, 0, 1],
    "rfs_days": [800, 250, 1200, 430, 600, 310, 500, 900],
    "event": [0, 1, 0, 1, 1, 0, 1, 0]
})

cox_data

   age  hpv_positive  rfs_days  event
0   63             1       800      0
1   55             0       250      1
2   71             1      1200      0
3   49             1       430      1
4   66             0       600      1
5   58             1       310      0
6   74             0       500      1
7   52             1       900      0

In [3]:
cph = CoxPHFitter()

cph.fit(
    cox_data,
    duration_col="rfs_days",
    event_col="event"
)

cph.print_summary()

<lifelines.CoxPHFitter: fitted with 8 total observations, 4 right-censored observations>
             duration col = 'rfs_days'
                event col = 'event'
      baseline estimation = breslow
   number of observations = 8
number of events observed = 4
   partial log-likelihood = -3.88
         time fit was run = 2026-10-04 19:12:54 UTC

---
              coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
age          -0.18      0.83      0.13           -0.44            0.08                0.64                1.08
hpv_positive -3.78      0.02      2.12           -7.95            0.38                0.00                1.46

              cmp to     z    p  -log2(p)
covariate
age             0.00 -1.39 0.16      2.61
hpv_positive    0.00 -1.78 0.07      3.74
---
Concordance = 0.84
Partial AIC = 11.75
log-likelihood ratio test = 5.98 on 2 df
-log2(p) of ll-ratio test = 4.32

In [4]:
cph.check_assumptions(cox_data, p_value_threshold=0.05)

Proportional hazard assumption looks okay.

[]